export const homeData = [
  {
    id: 1,
    name: "Sand Dust",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/blog/3.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "skull island",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Pirates Sea",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Sand Dust",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]

export const MovieGenres=[
  {
    id: 1,
    genres: "Action",
    cover: "../images/genres/action.jpg"
  },
  {
    id: 2,
    genres: "Adventures",
    cover: "../images/genres/adventures.jpg"
  },
  {
    id: 3,
    genres: "Animation",
    cover: "../images/genres/animation.jpg"
  },
  {
    id: 4,
    genres: "Biography",
    cover: "../images/genres/biography.jpg"
  },
  {
    id: 5,
    genres: "Comedy",
    cover: "../images/genres/Comedy.jpg"
  },
  {
    id: 6,
    genres: "Dama",
    cover: "../images/genres/dama.jpg"
  },
  {
    id: 7,
    genres: "Dram",
    cover: "../images/genres/Dram.jpg"
  },
  {
    id: 8,
    genres: "Fantasy",
    cover: "../images/genres/fantasy.jpg"
  },
  {
    id: 9,
    genres: "Mystery",
    cover: "../images/genres/Mystery.jpg"
  },
]
export const Blog=[
  {
    id: 1,
    name: "Emmy 2018: “Game of Throne”  featured having 22 nominee",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Movie",
    cover: "../images/blog/1.jpg",
    date: "january 1, 2019",
  },
  {
    id: 2,
    name: "Racing is about to show  you the beauty of Britain",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Tv series",
    cover: "../images/blog/2.jpg",
    date: "january 16, 2019",
  },
  {
    id: 3,
    name: "10 teams we can’t wait to  use in Soccer 2019",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Trailers",
    cover: "../images/blog/3.jpg",
    date: "january 16, 2019",
  },
  {
    id: 4,
    name: "Merghani Alonso wins  eSport League",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Historical",
    cover: "../images/blog/4.jpg",
    date: "january 1, 2019",
  },
  {
    id: 5,
    name: "10 Free Games with Gold  of July 2019 are out",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Movie",
    cover: "../images/blog/5.jpg",
    date: "january 1, 2019",
  },
  {
    id: 6,
    name: "A Free PC Game is still available Through AE",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Movie trailers",
    cover: "../images/blog/6.jpg",
    date: "january 1, 2019",
  },
  {
    id: 7,
    name: "Island 2 is still in deving, Magic confirms",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Trailer",
    cover: "../images/blog/7.jpg",
    date: "january 1, 2019",
  },
  {
    id: 8,
    name: "How turned Hot Wheels into sheer genius",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Trailers",
    cover: "../images/blog/8.jpg",
    date: "january 1, 2019",
  },
  {
    id: 9,
    name: "Drum Gum added in 4.5 Update",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Historical",
    cover: "../images/blog/9.jpg",
    date: "january 1, 2019",
  },
  {
    id: 10,
    name: "Grab free skin and loot From Phone",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Dramas",
    cover: "../images/blog/10.jpg",
    date: "january 1, 2019",
  },
  {
    id: 11,
    name: "Another free game from Mazaon Games",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Movie",
    cover: "../images/blog/11.jpg",
    date: "january 1, 2019",
  },
  {
    id: 12,
    name: "Thorin Used Anti-glay Slur",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Tv comedies",
    cover: "../images/blog/12.jpg",
    date: "january 1, 2019",
  },
  {
    id: 13,
    name: "Emmy 2018: “Game of Throne”  featured having 22 nominee",
    desc: "Praesent iaculis, purus ac vehicula mattis, arcu lorem blandit nisl, non laoreet dui mi eget elit. Donec porttitor ex vel augue maximus luctus. Vivamus finibus nibh eu nunc volutpat suscipit.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: "Movie",
    cover: "../images/blog/1.jpg",
    date: "january 1, 2019",
  },
]
